<script lang="ts">
	import LoadingState from './LoadingState.svelte';

	export let isThirdLoading: boolean;
	export let cardDefaultHtml: string;
	export let cardCustomHtml: string;
	export let cardCss: string;
	export let customizationWho: string;
	export let customizationWhat: string;
	export let stage: boolean[];
	export let disclaimerOpen: boolean;
	export let onShare: () => void;
	export let onCustomize: () => void;
	export let onDismissDisclaimer: () => void;
</script>

<div class="flex items-start">
	<div class="flex flex-col">
		{#if !isThirdLoading}
			<div class="flex mb-6 items-center">
				<div>
					<p class="font-heading grow text-lg font-medium text-gray-700">Your design cards are ready!</p>
				</div>
				<div class="grow">
					<button class="bg-gray-300 ms-5 hover:bg-gray-500 text-xs text-black font-medium py-1 px-1.5 rounded" on:click={onShare}>
						<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20" viewBox="0 0 30 30" class="icon">
							<path d="M 23 3 A 4 4 0 0 0 19 7 A 4 4 0 0 0 19.09375 7.8359375 L 10.011719 12.376953 A 4 4 0 0 0 7 11 A 4 4 0 0 0 3 15 A 4 4 0 0 0 7 19 A 4 4 0 0 0 10.013672 17.625 L 19.089844 22.164062 A 4 4 0 0 0 19 23 A 4 4 0 0 0 23 27 A 4 4 0 0 0 27 23 A 4 4 0 0 0 23 19 A 4 4 0 0 0 19.986328 20.375 L 10.910156 15.835938 A 4 4 0 0 0 11 15 A 4 4 0 0 0 10.90625 14.166016 L 19.988281 9.625 A 4 4 0 0 0 23 11 A 4 4 0 0 0 27 7 A 4 4 0 0 0 23 3 z"></path>
						</svg>
						<span>Share cards</span>
					</button>
				</div>
			</div>
		{/if}

		<div contenteditable="false" id="card_div" class="mb-8" bind:innerHTML={cardDefaultHtml}></div>
		<div contenteditable="false" id="card_div" bind:innerHTML={cardCustomHtml}></div>
		<div contenteditable="false" bind:innerHTML={cardCss}></div>
	</div>

	{#if isThirdLoading}
		<div class="px-6">
			<LoadingState title="Customizing cards.." subtitle="This may take up to 1 minute" size="50px" />
		</div>
	{:else}
		<form class="bg-white shadow-xl rounded-lg ml-8 p-3.5 mt-12 hidden sm:block">
			<div class="mb-5">
				<p class="mt-1 mb-1 text-xs font-medium leading-4">How do you want to customize these<br />cards for your own design work?</p>
				<p class="block mt-2 mb-4 font-light text-xs text-gray-900">In a plain language, describe:</p>
				<div class="mt-5">
					<label for="customization-what" class="block mb-2 font-light text-xs text-gray-900"><span class="font-medium">What</span> are you designing for?</label>
					<textarea id="customization-what" rows="2" class="block p-1.5 w-full text-xs text-gray-900 bg-gray-50 rounded-sm border border-gray-300 focus:ring-blue-500 focus:border-blue-500 text-xs" placeholder="ex) modality, pain points, client/company, domain, metric" bind:value={customizationWho}></textarea>
				</div>
				<div class="mt-4">
					<label for="customization-who" class="block mb-2 font-light text-xs text-gray-900"><span class="font-medium">Who</span> are you designing for?</label>
					<textarea id="customization-who" rows="2" class="block p-1.5 w-full text-xs text-gray-900 bg-gray-50 rounded-sm border border-gray-300 focus:ring-blue-500 focus:border-blue-500 text-xs" placeholder="ex) description of the target user, demographics, or persona" bind:value={customizationWhat}></textarea>
				</div>
				<div class="my-4">
					<p class="block mb-2 font-normal text-xs text-gray-900"><span class="font-medium">Why</span> do you need this? <span class="font-light">(optional)</span></p>
					<div class="flex mb-2">
						<label class="w-56 text-xs font-light">
							<input type="checkbox" bind:checked={stage[0]} />
							<span class="font-normal ps-1">Research</span>: Investigating the problem space design is intended to address
						</label>
					</div>
					<div class="flex mb-2">
						<label class="w-56 text-xs font-light">
							<input type="checkbox" bind:checked={stage[1]} />
							<span class="font-normal ps-1">Ideate</span>: Generating design ideas through creative brainstorming
						</label>
					</div>
					<div class="flex">
						<label class="w-56 text-xs font-light">
							<input type="checkbox" bind:checked={stage[2]} />
							<span class="font-normal ps-1">Evaluate</span>: Assessing if and how people can use the design solution
						</label>
					</div>
				</div>
			</div>
			<div class="flex text-center justify-center">
				<button class="bg-gray-300 hover:bg-slate-500 text-black font-medium text-xs py-1.5 px-3 rounded focus:outline-none focus:shadow-outline" type="button" on:click={onCustomize}>
					Customize!
				</button>
			</div>
		</form>
	{/if}
</div>

{#if !disclaimerOpen}
	<div class="fixed mx-8 my-3 rounded-lg bottom-0 px-5 py-3 bg-white drop-shadow-xl flex flex-row">
		<p class="text-xs"><span class="font-bold mr-1">ⓘ Disclaimer</span> Some components of these cards are generated by generative AI models (i.e., GPT, DALL-E), which can sometimes produce false, misleading information. Contents presented on the cards do not necessarily reflect the original intent of the authors. This interface is a research prototype, and the generated cards are meant as inspiration and the user should validate against the original paper.</p>
		<button class="text-xl align-center ml-2 cursor-pointer alert-del" on:click={onDismissDisclaimer}>&times;</button>
	</div>
{/if}

<style>
	.icon {
		width: 15px;
		display: inline;
		margin-right: 5px;
		position: relative;
	}
</style>
